export const SET_ONE_TASK= "SET_ONE_TASK"
export const SET_ALL_TASKS= "SET_ALL_TASKS"
export const DELETE_TASK= "DELETE_TASK"
export const SET_CURRENT_USER= "SET_CURRENT_USER"
export const SET_ALL_USERS= "SET_ALL_USERS"

